[package]
name = "toti"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
thiserror = { version = "1" }
syn = { version = "2", features = ["full", "extra-traits"] }
quote = { version = "1" }
proc-macro2 = { version = "1" }
